"""
Replace startups_data.json with 30 realistic startup profiles.
Run: python add_startups.py
"""
import json, os, random

DATA_PATH = os.path.join(os.path.dirname(__file__), 'data', 'startups_data.json')

STARTUPS = [
  {
    "id": "startup-001",
    "name": "NeuroLedger AI",
    "tagline": "Real-time fraud detection for cross-border payments using graph neural networks",
    "industry": "FinTech",
    "stage": "Series A",
    "founded_year": 2021,
    "location": "Bangalore, India",
    "team_size": 22,
    "problem_solved": "Cross-border payment fraud costs global banks $48B annually. Current rule-based systems have 30% false-positive rates that freeze legitimate transactions.",
    "proposed_solution": "Graph neural network trained on 500M transaction edges detecting fraud in <50ms with 94% accuracy and 8% false-positive rate — a 3x improvement over industry average.",
    "target_market": "Tier 1 and Tier 2 banks processing international wire transfers",
    "revenue_model": "SaaS per-transaction fee ($0.004/transaction) + annual enterprise license",
    "traction": {"mrr_usd": 48000, "users": 12, "pilot_partners": ["HDFC Bank", "Yes Bank", "Axis Bank"]},
    "funding_ask_usd": 3000000,
    "equity_offered_percent": 12,
    "use_of_funds": "Model training on larger datasets, RBI regulatory sandbox, EU GDPR compliance, sales team in Singapore",
    "potential_rating": "High",
    "submitted_at": "2024-08-12T09:00:00Z"
  },
  {
    "id": "startup-002",
    "name": "CelluMatrix Health",
    "tagline": "AI pathology for early-stage cancer detection from routine blood panels",
    "industry": "HealthTech",
    "stage": "Seed",
    "founded_year": 2022,
    "location": "Hyderabad, India",
    "team_size": 14,
    "problem_solved": "78% of cancers are diagnosed at Stage 3 or 4 when treatment costs are 6x higher and survival rates are 40% lower.",
    "proposed_solution": "Multimodal AI model analyzing 47 biomarkers from standard CBC blood panels to flag cancer risk 12–18 months before clinical symptoms.",
    "target_market": "Diagnostic labs and preventive health platforms in India and Southeast Asia",
    "revenue_model": "B2B SaaS — per-test fee (₹120/test) to diagnostic labs",
    "traction": {"mrr_usd": 8500, "users": 3, "pilot_partners": ["Metropolis Healthcare", "Thyrocare"]},
    "funding_ask_usd": 1200000,
    "equity_offered_percent": 10,
    "use_of_funds": "Clinical trial data collection across 10,000 patients, CDSCO regulatory approval, model accuracy improvement",
    "potential_rating": "High",
    "submitted_at": "2024-07-20T11:00:00Z"
  },
  {
    "id": "startup-003",
    "name": "OmniStore Robotics",
    "tagline": "Micro-fulfillment robots for dark store last-mile grocery delivery",
    "industry": "Retail Tech",
    "stage": "Series A",
    "founded_year": 2020,
    "location": "Pune, India",
    "team_size": 38,
    "problem_solved": "Quick-commerce dark stores spend 42% of operating costs on picking labor. Manual picking limits order throughput to 300 orders/hour per store.",
    "proposed_solution": "Autonomous robot fleet achieving 1,200 orders/hour per dark store at 60% lower picking cost using custom vision-guided arms.",
    "target_market": "Blinkit, Zepto, Swiggy Instamart, Amazon Fresh dark store operators",
    "revenue_model": "Robotics-as-a-Service (RaaS) — ₹8/order fulfilled + annual maintenance",
    "traction": {"mrr_usd": 72000, "users": 4, "pilot_partners": ["Zepto", "BigBasket"]},
    "funding_ask_usd": 5000000,
    "equity_offered_percent": 15,
    "use_of_funds": "Robot manufacturing scale-up, Tamil Nadu facility, 10 new dark store deployments",
    "potential_rating": "High",
    "submitted_at": "2024-06-15T08:30:00Z"
  },
  {
    "id": "startup-004",
    "name": "UrbanGrid PropTech",
    "tagline": "AI-driven commercial real estate valuation and lease optimization for enterprise tenants",
    "industry": "PropTech",
    "stage": "Pre-Seed",
    "founded_year": 2023,
    "location": "Mumbai, India",
    "team_size": 6,
    "problem_solved": "Enterprise tenants overpay 15-25% on commercial leases due to information asymmetry between tenants and landlords.",
    "proposed_solution": "ML model trained on 2M+ lease transactions providing real-time comparable lease benchmarks and AI-negotiation playbooks.",
    "target_market": "Fortune 500 companies expanding office footprint in tier-1 Indian cities",
    "revenue_model": "Success fee (1.5% of annual contract value saved) + SaaS subscription",
    "traction": {"mrr_usd": 2100, "users": 8, "pilot_partners": ["Infosys", "TCS (pilot)"]},
    "funding_ask_usd": 500000,
    "equity_offered_percent": 8,
    "use_of_funds": "Data acquisition partnerships, product development, sales hire",
    "potential_rating": "Medium",
    "submitted_at": "2024-09-01T10:00:00Z"
  },
  {
    "id": "startup-005",
    "name": "AeroVolt Logistics",
    "tagline": "Electric cargo drone network for last-mile pharmaceutical delivery in Tier 3 cities",
    "industry": "DeepTech / Logistics",
    "stage": "Seed",
    "founded_year": 2022,
    "location": "Chennai, India",
    "team_size": 18,
    "problem_solved": "280M Indians in rural and semi-urban areas receive medicines 72+ hours late due to broken cold-chain logistics.",
    "proposed_solution": "Fixed-wing electric cargo drones with 25km range and temperature-controlled payload delivering medicines in under 90 minutes.",
    "target_market": "Apollo Pharmacy, MedPlus, government AYUSH health programs",
    "revenue_model": "Per-delivery fee (₹85/delivery) + fleet-as-a-service for pharmacy chains",
    "traction": {"mrr_usd": 11000, "users": 5, "pilot_partners": ["Apollo Pharmacy", "Telangana Govt Health Dept"]},
    "funding_ask_usd": 2000000,
    "equity_offered_percent": 12,
    "use_of_funds": "DGCA type certification, fleet expansion to 50 drones, 3 new state partnerships",
    "potential_rating": "High",
    "submitted_at": "2024-05-30T14:00:00Z"
  },
  {
    "id": "startup-006",
    "name": "CarbonTrack.ai",
    "tagline": "Automated carbon footprint accounting and offset marketplace for SMEs",
    "industry": "ClimaTech",
    "stage": "Seed",
    "founded_year": 2022,
    "location": "Bengaluru, India",
    "team_size": 12,
    "problem_solved": "90% of SMEs cannot afford the $50,000+ cost of traditional carbon audits, blocking access to ESG financing and export markets.",
    "proposed_solution": "API-first platform that auto-calculates Scope 1/2/3 emissions from accounting data (Tally, Zoho Books) and connects to verified offset projects.",
    "target_market": "Textile, pharma, and auto-component exporters needing EU CBAM compliance",
    "revenue_model": "SaaS (₹4,999/month) + 2% transaction fee on offset purchases",
    "traction": {"mrr_usd": 14000, "users": 180, "pilot_partners": ["Tirupur Exporters Association", "FICCI SME"]},
    "funding_ask_usd": 1500000,
    "equity_offered_percent": 10,
    "use_of_funds": "EU CBAM compliance module, carbon registry integrations, 500 customer expansion",
    "potential_rating": "High",
    "submitted_at": "2024-04-10T09:00:00Z"
  },
  {
    "id": "startup-007",
    "name": "SkillForge",
    "tagline": "AI-personalized vocational training platform for blue-collar reskilling",
    "industry": "EdTech",
    "stage": "Series A",
    "founded_year": 2020,
    "location": "Delhi NCR, India",
    "team_size": 45,
    "problem_solved": "12 million Indians enter the workforce annually with skill gaps mismatched to employer demand. 68% of graduates are unemployable in their field.",
    "proposed_solution": "Mobile-first platform delivering job-specific microlearning in 14 regional languages with AR simulation for hands-on trade skills.",
    "target_market": "ITI graduates, gig workers, and blue-collar workers in manufacturing and construction",
    "revenue_model": "B2B enterprise (₹2,500/learner/year) + B2C freemium with ₹299/month premium",
    "traction": {"mrr_usd": 95000, "users": 185000, "pilot_partners": ["Larsen & Toubro", "Tata Steel", "MSDE (Ministry of Skill)"]},
    "funding_ask_usd": 8000000,
    "equity_offered_percent": 18,
    "use_of_funds": "Content creation in 6 new trades, Southeast Asia expansion, AI assessment engine",
    "potential_rating": "High",
    "submitted_at": "2024-03-22T08:00:00Z"
  },
  {
    "id": "startup-008",
    "name": "AgriSense",
    "tagline": "IoT soil intelligence network for precision irrigation and fertilizer optimization",
    "industry": "AgriTech",
    "stage": "Seed",
    "founded_year": 2021,
    "location": "Nashik, Maharashtra",
    "team_size": 16,
    "problem_solved": "Indian farmers waste 35% of irrigation water and overfertilize by 40% due to lack of real-time soil data, costing ₹18,000/year per farmer.",
    "proposed_solution": "Solar-powered IoT soil sensors (NPK + moisture + pH) with AI recommendations delivered via WhatsApp — no smartphone app required.",
    "target_market": "Grape, onion, and cotton farmers across Maharashtra and Karnataka",
    "revenue_model": "Hardware sale (₹3,500 sensor) + ₹199/month subscription for AI recommendations",
    "traction": {"mrr_usd": 18000, "users": 2800, "pilot_partners": ["Maharashtra State Agriculture Dept", "FMC Corporation"]},
    "funding_ask_usd": 1800000,
    "equity_offered_percent": 11,
    "use_of_funds": "Sensor manufacturing at scale, 10,000 farmer expansion, Tamil Nadu and AP entry",
    "potential_rating": "High",
    "submitted_at": "2024-02-14T10:00:00Z"
  },
  {
    "id": "startup-009",
    "name": "MedBridge Connect",
    "tagline": "Telemedicine platform for rural India with offline-first AI triage",
    "industry": "HealthTech",
    "stage": "Pre-Seed",
    "founded_year": 2023,
    "location": "Bhopal, Madhya Pradesh",
    "team_size": 8,
    "problem_solved": "600M Indians live more than 5km from the nearest doctor. 73% of rural consultations are for 5 common treatable conditions.",
    "proposed_solution": "Offline-capable tablet app with AI symptom checker (trained on ICD-11 codes) enabling ASHA workers to triage patients and initiate telemedicine consultations.",
    "target_market": "National Health Mission ASHA and ANM networks across 6 high-priority states",
    "revenue_model": "Government B2G contract (₹80/consultation) + pharmaceutical partnership revenue",
    "traction": {"mrr_usd": 3200, "users": 240, "pilot_partners": ["MP State Health Dept", "WHO India"]},
    "funding_ask_usd": 600000,
    "equity_offered_percent": 9,
    "use_of_funds": "Offline AI model improvement, 1000 ASHA worker onboarding, regulatory approval",
    "potential_rating": "Medium",
    "submitted_at": "2024-09-10T11:00:00Z"
  },
  {
    "id": "startup-010",
    "name": "FlexWork AI",
    "tagline": "AI scheduling and compliance engine for distributed workforce management",
    "industry": "HR Tech / SaaS",
    "stage": "Series A",
    "founded_year": 2021,
    "location": "Singapore",
    "team_size": 31,
    "problem_solved": "Companies with 5000+ shift workers lose $2.3M annually to scheduling inefficiencies, compliance violations, and overtime mismanagement.",
    "proposed_solution": "AI scheduling engine that optimizes 10,000+ employee shifts across 50+ compliance rule types in under 3 minutes, with real-time WhatsApp notifications.",
    "target_market": "Retail chains, BPOs, hospitals, and manufacturing units across Southeast Asia",
    "revenue_model": "SaaS — $12/employee/month with annual enterprise contracts",
    "traction": {"mrr_usd": 142000, "users": 15, "pilot_partners": ["FairPrice Group", "Parkway Health", "DHL SEA"]},
    "funding_ask_usd": 6000000,
    "equity_offered_percent": 14,
    "use_of_funds": "India market entry, AI compliance rule engine for 8 new jurisdictions, enterprise sales team",
    "potential_rating": "High",
    "submitted_at": "2024-01-18T09:30:00Z"
  },
  {
    "id": "startup-011",
    "name": "GreenRoute EV",
    "tagline": "EV fleet management and charging optimization for commercial logistics companies",
    "industry": "ClimaTech / Mobility",
    "stage": "Seed",
    "founded_year": 2022,
    "location": "Gurugram, India",
    "team_size": 14,
    "problem_solved": "Fleet operators switching to EVs suffer 28% route efficiency loss due to range anxiety and unoptimized charging station scheduling.",
    "proposed_solution": "AI route optimization considering real-time battery state, charging station availability, and delivery windows — extending effective EV range by 35%.",
    "target_market": "Ekart, Delhivery, BlueDart transitioning last-mile fleets to EV",
    "revenue_model": "SaaS per-vehicle per-month (₹2,200/vehicle) + charging station API revenue",
    "traction": {"mrr_usd": 22000, "users": 6, "pilot_partners": ["Ekart Logistics", "BPCL EV charging network"]},
    "funding_ask_usd": 2500000,
    "equity_offered_percent": 13,
    "use_of_funds": "V2G (vehicle-to-grid) API integration, 500 vehicle fleet expansion, Pune and Chennai entry",
    "potential_rating": "High",
    "submitted_at": "2024-08-05T10:00:00Z"
  },
  {
    "id": "startup-012",
    "name": "LegalEase.ai",
    "tagline": "AI contract analysis and clause risk-flagging for India's SME sector",
    "industry": "LegalTech",
    "stage": "Pre-Seed",
    "founded_year": 2023,
    "location": "Kolkata, India",
    "team_size": 7,
    "problem_solved": "Indian SMEs sign 200+ contracts annually without legal review due to ₹15,000+ per hour lawyer costs, creating hidden liability exposure.",
    "proposed_solution": "LLM fine-tuned on Indian contract law extracting key clauses, flagging jurisdiction-specific risks, and suggesting standard safe alternatives in plain English.",
    "target_market": "SMEs in manufacturing, export, and IT services with 50-500 employee size",
    "revenue_model": "Freemium SaaS — ₹2,499/month for unlimited contract reviews",
    "traction": {"mrr_usd": 4800, "users": 320, "pilot_partners": ["FICCI LegalTech", "Bar Council of India (observer)"]},
    "funding_ask_usd": 400000,
    "equity_offered_percent": 8,
    "use_of_funds": "Legal dataset expansion, BCI compliance certification, 1000 SME customer target",
    "potential_rating": "Medium",
    "submitted_at": "2024-09-15T09:00:00Z"
  },
  {
    "id": "startup-013",
    "name": "Plastika Recycling",
    "tagline": "Chemical recycling of mixed plastic waste into virgin-quality polymer pellets",
    "industry": "ClimaTech / Manufacturing",
    "stage": "Seed",
    "founded_year": 2021,
    "location": "Ahmedabad, India",
    "team_size": 20,
    "problem_solved": "Only 9% of plastic is recycled globally. Mixed plastic waste (multi-layer packaging) cannot be mechanically recycled and goes to landfill.",
    "proposed_solution": "Proprietary pyrolysis process converting mixed plastic waste into HDPE/PP pellets at 85% yield rate, accepted by major polymer manufacturers.",
    "target_market": "FMCG companies (Unilever, P&G) with EPR (Extended Producer Responsibility) compliance mandates",
    "revenue_model": "Waste tipping fees (₹4/kg input) + polymer pellet sales (₹65/kg output)",
    "traction": {"mrr_usd": 31000, "users": 8, "pilot_partners": ["Unilever India", "GPCB (Gujarat Pollution Control)"]},
    "funding_ask_usd": 3500000,
    "equity_offered_percent": 15,
    "use_of_funds": "10-tonne/day plant construction, BIS polymer quality certification, 3 FMCG offtake agreements",
    "potential_rating": "High",
    "submitted_at": "2024-07-01T08:00:00Z"
  },
  {
    "id": "startup-014",
    "name": "NutriBot Kitchen",
    "tagline": "Automated cloud kitchen robotics reducing food preparation cost by 55%",
    "industry": "FoodTech / Robotics",
    "stage": "Seed",
    "founded_year": 2022,
    "location": "Hyderabad, India",
    "team_size": 16,
    "problem_solved": "Cloud kitchens have 35-40% labor costs that make unit economics negative at under 200 orders/day. Consistent quality requires skilled chefs who are expensive and scarce.",
    "proposed_solution": "Robotic cooking arms with computer vision quality control producing 400 meals/hour with <2% defect rate and zero food waste.",
    "target_market": "Swiggy, Zomato, and McDonald's cloud kitchen operators in metro cities",
    "revenue_model": "RaaS — ₹12/meal produced + monthly maintenance contract",
    "traction": {"mrr_usd": 19000, "users": 3, "pilot_partners": ["Rebel Foods", "Swiggy Access (pilot)"]},
    "funding_ask_usd": 2800000,
    "equity_offered_percent": 14,
    "use_of_funds": "Robot manufacturing, FSSAI certification, 10 cloud kitchen deployments",
    "potential_rating": "Medium",
    "submitted_at": "2024-06-20T10:00:00Z"
  },
  {
    "id": "startup-015",
    "name": "CreditSaathi",
    "tagline": "Vernacular AI loan advisor for first-time borrowers in Bharat",
    "industry": "FinTech",
    "stage": "Seed",
    "founded_year": 2022,
    "location": "Jaipur, Rajasthan",
    "team_size": 11,
    "problem_solved": "250M first-time credit users in rural India are exploited by informal moneylenders charging 40-120% annual interest due to lack of financial literacy.",
    "proposed_solution": "WhatsApp-native AI chatbot in Hindi, Tamil, and 10 regional languages guiding users to the most suitable formal credit product (Mudra, PM SVANidhi, PMFBY).",
    "target_market": "Jan Dhan account holders, SHG members, and kirana store owners",
    "revenue_model": "Lead generation fee from NBFC and MFI partners (₹400/successful loan disbursement)",
    "traction": {"mrr_usd": 7200, "users": 18000, "pilot_partners": ["Ujjivan SFB", "Cashkumar MFI", "Arohan Financial"]},
    "funding_ask_usd": 900000,
    "equity_offered_percent": 9,
    "use_of_funds": "8 new language models, RBI NBFC partnership compliance, 100,000 user milestone",
    "potential_rating": "High",
    "submitted_at": "2024-05-10T11:00:00Z"
  },
  {
    "id": "startup-016",
    "name": "QuantumShield Cybersec",
    "tagline": "Post-quantum cryptography upgrade layer for legacy enterprise banking systems",
    "industry": "Cybersecurity",
    "stage": "Pre-Seed",
    "founded_year": 2023,
    "location": "Bengaluru, India",
    "team_size": 9,
    "problem_solved": "Quantum computers will break current RSA/ECC encryption by 2030. 85% of bank core systems are not quantum-resistant and cannot be replaced in time.",
    "proposed_solution": "Middleware layer implementing NIST-certified post-quantum algorithms (CRYSTALS-Kyber, FALCON) without requiring legacy system replacement — zero downtime migration.",
    "target_market": "RBI-regulated banks and SEBI-regulated brokerages with 10+ year legacy system cycles",
    "revenue_model": "Annual enterprise license (₹45L/year per bank) + professional services",
    "traction": {"mrr_usd": 5500, "users": 2, "pilot_partners": ["Union Bank of India (PoC)", "SEBI FinTech Regulatory Sandbox"]},
    "funding_ask_usd": 1000000,
    "equity_offered_percent": 10,
    "use_of_funds": "CERT-In security audit, RBI compliance certification, 5 bank pilot conversions",
    "potential_rating": "High",
    "submitted_at": "2024-09-20T09:30:00Z"
  },
  {
    "id": "startup-017",
    "name": "SolarSage Energy",
    "tagline": "AI-optimized community solar microgrids for unelectrified industrial clusters",
    "industry": "ClimaTech / Energy",
    "stage": "Series A",
    "founded_year": 2020,
    "location": "Coimbatore, Tamil Nadu",
    "team_size": 28,
    "problem_solved": "80,000 MSME industrial clusters in India pay ₹12-18/unit for diesel gensets due to grid unreliability, spending 18% of revenue on energy.",
    "proposed_solution": "Shared solar microgrid with AI demand forecasting and battery management, delivering 24x7 power at ₹5.50/unit — 55% cheaper than diesel.",
    "target_market": "Textile, foundry, and food processing MSME clusters in Tamil Nadu, Gujarat, and MP",
    "revenue_model": "Energy-as-a-Service (EaaS) — per-unit billing with 15-year power purchase agreements",
    "traction": {"mrr_usd": 88000, "users": 14, "pilot_partners": ["SIDBI Energy Finance", "Tamil Nadu MSME Dept"]},
    "funding_ask_usd": 7000000,
    "equity_offered_percent": 16,
    "use_of_funds": "3 new cluster deployments (Maharashtra, Gujarat), battery storage capacity doubling, DISCOM grid integration",
    "potential_rating": "High",
    "submitted_at": "2024-04-25T10:00:00Z"
  },
  {
    "id": "startup-018",
    "name": "HealthKart Diagnostics",
    "tagline": "At-home blood collection network with 4-hour turnaround in Tier 2 cities",
    "industry": "HealthTech",
    "stage": "Seed",
    "founded_year": 2022,
    "location": "Nagpur, Maharashtra",
    "team_size": 13,
    "problem_solved": "Tier 2 and 3 city residents travel 25km average for blood tests and wait 48-72 hours for results, leading to delayed diagnosis.",
    "proposed_solution": "Hub-and-spoke model with trained phlebotomist network and mobile micro-lab vans delivering results in 4 hours via WhatsApp.",
    "target_market": "Working professionals and senior citizens in 30 tier-2 cities across Maharashtra and MP",
    "revenue_model": "Per-test fee (₹300-2500 depending on panel) + corporate health package subscription",
    "traction": {"mrr_usd": 24000, "users": 4200, "pilot_partners": ["Star Health Insurance", "Manipal Health (franchise)"]},
    "funding_ask_usd": 2200000,
    "equity_offered_percent": 12,
    "use_of_funds": "15 new city expansions, mobile lab van fleet, NABL accreditation",
    "potential_rating": "Medium",
    "submitted_at": "2024-08-18T09:00:00Z"
  },
  {
    "id": "startup-019",
    "name": "PolyMed Prosthetics",
    "tagline": "3D-printed affordable prosthetic limbs for amputees in developing markets",
    "industry": "HealthTech / DeepTech",
    "stage": "Seed",
    "founded_year": 2021,
    "location": "Jaipur, India",
    "team_size": 15,
    "problem_solved": "35M+ amputees in developing countries cannot afford conventional prosthetics ($5,000-20,000). Government-provided limbs have 14-month waiting lists.",
    "proposed_solution": "AI-scanned and 3D-printed custom prosthetics at ₹8,000 ($95) using recycled PETG polymer — delivered in 72 hours.",
    "target_market": "Government prosthetic schemes (ADIP), NGOs, and WHO humanitarian aid programs",
    "revenue_model": "Direct-to-patient (₹8,000) + B2G government ADIP scheme contracts at scale",
    "traction": {"mrr_usd": 12000, "users": 420, "pilot_partners": ["Jaipur Foot (NROI)", "Ministry of Social Justice ADIP scheme"]},
    "funding_ask_usd": 1500000,
    "equity_offered_percent": 11,
    "use_of_funds": "FDA CE mark certification for export, 5 district hospital partnerships, carbon-composite socket development",
    "potential_rating": "High",
    "submitted_at": "2024-03-08T10:00:00Z"
  },
  {
    "id": "startup-020",
    "name": "DataDhar Platform",
    "tagline": "Federated data marketplace enabling privacy-preserving analytics for enterprises",
    "industry": "B2B SaaS / Data",
    "stage": "Pre-Seed",
    "founded_year": 2023,
    "location": "Bengaluru, India",
    "team_size": 7,
    "problem_solved": "Enterprises hold siloed datasets that could generate $2.3T in value through cross-industry analytics but cannot share due to PDPB and GDPR privacy laws.",
    "proposed_solution": "Federated learning platform allowing organizations to train shared ML models without ever exposing raw data — privacy by design, legally compliant.",
    "target_market": "Banking, telecom, and e-commerce enterprises wanting to enrich customer data without data sharing",
    "revenue_model": "SaaS platform fee (₹8L/month for up to 5 federation partners) + consulting",
    "traction": {"mrr_usd": 6000, "users": 3, "pilot_partners": ["Jio Platforms (PoC)", "NASSCOM Data Council"]},
    "funding_ask_usd": 800000,
    "equity_offered_percent": 9,
    "use_of_funds": "PDPB compliance certification, 3 federation network launches, ML research team hiring",
    "potential_rating": "High",
    "submitted_at": "2024-09-25T09:00:00Z"
  },
  {
    "id": "startup-021",
    "name": "BuildRight AI",
    "tagline": "Construction project monitoring using satellite imagery and computer vision",
    "industry": "PropTech / Construction",
    "stage": "Seed",
    "founded_year": 2022,
    "location": "Noida, India",
    "team_size": 12,
    "problem_solved": "Infrastructure projects in India average 57% cost overruns and 3-year delays due to lack of real-time progress monitoring across 500+ sites.",
    "proposed_solution": "Weekly satellite imagery + on-site drone captures analyzed by CV models to detect construction progress, safety violations, and material theft in real-time.",
    "target_market": "NHAI highway projects, Smart Cities Mission, and large real estate developers",
    "revenue_model": "SaaS per-site (₹85,000/site/year) + risk analytics premium tier",
    "traction": {"mrr_usd": 28000, "users": 5, "pilot_partners": ["NHAI (3 highway segments)", "L&T Realty"]},
    "funding_ask_usd": 2500000,
    "equity_offered_percent": 13,
    "use_of_funds": "High-resolution satellite imagery partnerships, 50-site expansion, PMGSY rural roads program bid",
    "potential_rating": "High",
    "submitted_at": "2024-07-12T10:00:00Z"
  },
  {
    "id": "startup-022",
    "name": "AquaLens",
    "tagline": "IoT groundwater quality monitoring network for rural municipalities",
    "industry": "ClimaTech / Water",
    "stage": "Pre-Seed",
    "founded_year": 2023,
    "location": "Jhansi, Uttar Pradesh",
    "team_size": 6,
    "problem_solved": "91M Indians consume arsenic-contaminated groundwater. Municipalities test wells only quarterly, allowing contamination spikes to go undetected for months.",
    "proposed_solution": "Solar-powered IoT water sensors testing 12 contamination parameters every 6 hours with automated SMS alerts to village water committee members.",
    "target_market": "Jal Jeevan Mission municipalities, WHO rural water programs, state Jal Boards",
    "revenue_model": "B2G sensor lease (₹1,200/sensor/month) + water quality dashboard SaaS for municipalities",
    "traction": {"mrr_usd": 2800, "users": 12, "pilot_partners": ["UP Jal Nigam", "UNICEF India Water Safety"]},
    "funding_ask_usd": 450000,
    "equity_offered_percent": 8,
    "use_of_funds": "500 sensor manufacturing, 5 district Jal Jeevan Mission contracts, BIS sensor certification",
    "potential_rating": "Medium",
    "submitted_at": "2024-09-28T09:00:00Z"
  },
  {
    "id": "startup-023",
    "name": "InsureBot",
    "tagline": "Conversational AI for insurance claim automation and fraud detection",
    "industry": "InsurTech",
    "stage": "Seed",
    "founded_year": 2022,
    "location": "Mumbai, India",
    "team_size": 17,
    "problem_solved": "Indian insurance companies process claims manually, costing ₹1,800/claim and taking 14 days average. Fraud costs the industry ₹45,000 crore annually.",
    "proposed_solution": "WhatsApp-native claims bot with document OCR, image damage assessment, and ML fraud scoring — settling 80% of motor claims in under 4 hours without human intervention.",
    "target_market": "IRDAI-regulated general insurance companies processing 10M+ motor claims annually",
    "revenue_model": "Per-claim processed fee (₹180/claim) + annual enterprise license",
    "traction": {"mrr_usd": 38000, "users": 4, "pilot_partners": ["HDFC ERGO", "New India Assurance (PoC)"]},
    "funding_ask_usd": 2000000,
    "equity_offered_percent": 12,
    "use_of_funds": "Health claims module launch, IRDAI tech sandbox approval, 10 insurer onboarding",
    "potential_rating": "High",
    "submitted_at": "2024-06-08T10:00:00Z"
  },
  {
    "id": "startup-024",
    "name": "WeaveMind Textiles",
    "tagline": "AI quality inspection for power loom fabric defect detection",
    "industry": "Manufacturing / AI",
    "stage": "Pre-Seed",
    "founded_year": 2023,
    "location": "Surat, Gujarat",
    "team_size": 8,
    "problem_solved": "Textile mills reject 8-12% of fabric production due to weaving defects missed during manual inspection. This costs India's $40B textile export industry $3.2B annually.",
    "proposed_solution": "High-speed camera + custom CNN detecting 23 defect types in real-time at 1,200m of fabric per hour — 4x faster than human inspection with 97% accuracy.",
    "target_market": "Surat power loom cluster (600,000 looms) and Tirupur knitwear exporters",
    "revenue_model": "Machine-lease model (₹18,000/month per inspection unit) + defect analytics SaaS",
    "traction": {"mrr_usd": 9000, "users": 8, "pilot_partners": ["Texcraft Association Surat", "Garment Export Promotion Council"]},
    "funding_ask_usd": 700000,
    "equity_offered_percent": 9,
    "use_of_funds": "Manufacturing 50 inspection units, EU textile import quality standard compliance, Tirupur cluster entry",
    "potential_rating": "Medium",
    "submitted_at": "2024-09-05T09:00:00Z"
  },
  {
    "id": "startup-025",
    "name": "Finflow Trade",
    "tagline": "Supply chain finance platform for MSME exporters against confirmed purchase orders",
    "industry": "FinTech / Trade Finance",
    "stage": "Seed",
    "founded_year": 2022,
    "location": "Ahmedabad, India",
    "team_size": 14,
    "problem_solved": "MSME exporters wait 60-120 days for payment after shipment, creating a $500B working capital gap that forces them to reject large orders.",
    "proposed_solution": "Instant credit against confirmed Walmart/Amazon purchase orders using ML invoice validation and buyer creditworthiness scoring — funds in 24 hours.",
    "target_market": "1.4M MSME exporters on Amazon Global Selling, Flipkart Wholesale, and direct EU/US buyers",
    "revenue_model": "2.1% discount fee on invoice value (annualized 8-10% yield) + platform subscription",
    "traction": {"mrr_usd": 55000, "users": 340, "pilot_partners": ["Amazon Global Selling India", "ECGC (Export Credit Guarantee)"]},
    "funding_ask_usd": 4000000,
    "equity_offered_percent": 14,
    "use_of_funds": "NBFC license application, ₹50 crore lending book growth, EU market entry",
    "potential_rating": "High",
    "submitted_at": "2024-05-18T10:00:00Z"
  },
  {
    "id": "startup-026",
    "name": "NeuroPath Education",
    "tagline": "Adaptive K-12 learning platform with dyslexia and dyscalculia detection",
    "industry": "EdTech",
    "stage": "Pre-Seed",
    "founded_year": 2023,
    "location": "Kochi, Kerala",
    "team_size": 9,
    "problem_solved": "10-15% of children have learning disabilities like dyslexia that go undiagnosed for years due to ₹12,000 neuropsychological assessment costs, causing permanent academic underperformance.",
    "proposed_solution": "Gamified learning platform screening children for 8 learning disabilities during play, providing personalized learning paths and teacher alerts within the first 30 days.",
    "target_market": "CBSE and ICSE private schools for grades 1-5 across Kerala, Karnataka, and Tamil Nadu",
    "revenue_model": "B2B school license (₹350/student/year) + B2C parent premium at ₹499/month",
    "traction": {"mrr_usd": 5200, "users": 1800, "pilot_partners": ["Kendriya Vidyalaya Sangathan (3 schools)", "National Institute of Mental Health"]},
    "funding_ask_usd": 600000,
    "equity_offered_percent": 9,
    "use_of_funds": "Clinical validation study, 100 school expansion, Hindi and Tamil language version",
    "potential_rating": "High",
    "submitted_at": "2024-09-18T10:00:00Z"
  },
  {
    "id": "startup-027",
    "name": "TradeVault DeFi",
    "tagline": "Compliant DeFi infrastructure for institutional commodity trading on blockchain",
    "industry": "FinTech / Web3",
    "stage": "Seed",
    "founded_year": 2022,
    "location": "Dubai, UAE",
    "team_size": 16,
    "problem_solved": "Commodity traders pay 3-5% in settlement fees and face T+5 settlement cycles on $8T annual physical commodity markets due to opaque intermediary infrastructure.",
    "proposed_solution": "VARA-regulated smart contract platform enabling institutional commodity delivery vs payment settlement in T+15 minutes with cryptographic ownership proofs.",
    "target_market": "Dubai Multi Commodities Centre (DMCC) members, Singapore SGX commodity traders",
    "revenue_model": "0.12% settlement fee per transaction + API license for commodity exchanges",
    "traction": {"mrr_usd": 32000, "users": 22, "pilot_partners": ["DMCC (MOU)", "Sucafina (coffee trader)"]},
    "funding_ask_usd": 3000000,
    "equity_offered_percent": 13,
    "use_of_funds": "VARA full license, Singapore MAS approval, gold and crude oil settlement modules",
    "potential_rating": "High",
    "submitted_at": "2024-04-30T09:00:00Z"
  },
  {
    "id": "startup-028",
    "name": "ClearSky Climate",
    "tagline": "Hyperlocal air quality forecasting API for industrial emission compliance",
    "industry": "ClimaTech / GovTech",
    "stage": "Pre-Seed",
    "founded_year": 2023,
    "location": "Delhi, India",
    "team_size": 8,
    "problem_solved": "Delhi NCR industries face ₹1 lakh/day fines for GRAP-4 violations they receive 0-2 hours notice for. Advance warning would save ₹850 crore annually in industry fines.",
    "proposed_solution": "Satellite AQ data + weather modeling providing 48-hour hyperlocal pollution forecasts at 500m resolution — 4x better spatial resolution than CPCB stations.",
    "target_market": "Delhi, Haryana, UP industrial estates; municipal corporations for GRAP enforcement",
    "revenue_model": "API subscription for industries (₹3L/year) + CPCB and municipal licensing",
    "traction": {"mrr_usd": 4100, "users": 28, "pilot_partners": ["CPCB (data partnership)", "Haryana HSPCB"]},
    "funding_ask_usd": 550000,
    "equity_offered_percent": 8,
    "use_of_funds": "Physical sensor network for model calibration, 5 state pollution board contracts, EU Copernicus data partnership",
    "potential_rating": "Medium",
    "submitted_at": "2024-09-22T09:00:00Z"
  },
  {
    "id": "startup-029",
    "name": "WheelHouse Mobility",
    "tagline": "Shared electric wheelchair subscription for hospital campuses and airports",
    "industry": "HealthTech / Mobility",
    "stage": "Pre-Seed",
    "founded_year": 2023,
    "location": "Bengaluru, India",
    "team_size": 5,
    "problem_solved": "Hospitals and airports spend ₹4.2L/year managing manual wheelchair fleets with 60% idle time, while patients wait 25 minutes for wheelchair assistance.",
    "proposed_solution": "IoT-enabled electric wheelchairs with QR scan self-service, GPS tracking, and automatic charging docks — reducing patient wait time to under 3 minutes.",
    "target_market": "NABH-accredited hospitals and AAI airports across India",
    "revenue_model": "Fleet-as-a-Service (₹6,500/wheelchair/month) with zero CapEx for hospitals",
    "traction": {"mrr_usd": 3800, "users": 4, "pilot_partners": ["Manipal Hospital Bengaluru", "Kempegowda International Airport (trial)"]},
    "funding_ask_usd": 450000,
    "equity_offered_percent": 8,
    "use_of_funds": "Manufacturing 200 units, 10 hospital onboardings, Hyderabad and Chennai expansion",
    "potential_rating": "Medium",
    "submitted_at": "2024-09-30T10:00:00Z"
  },
  {
    "id": "startup-030",
    "name": "SkyMind Satellite",
    "tagline": "Low-cost earth observation analytics for disaster early warning systems",
    "industry": "SpaceTech / GovTech",
    "stage": "Seed",
    "founded_year": 2021,
    "location": "Bengaluru, India",
    "team_size": 21,
    "problem_solved": "Flood and cyclone early warnings in India reach communities 12-24 hours before impact. 500m radar resolution misses localized flood buildup in 85% of events.",
    "proposed_solution": "SAR satellite imagery at 3m resolution with AI change-detection models providing 72-hour hyperlocal flood forecasts — 3x the accuracy of current NDRF systems.",
    "target_market": "NDMA, state disaster management authorities, World Bank DRR programs, UN OCHA",
    "revenue_model": "B2G analytics API (₹1.2 crore/state/year) + World Bank DRR project contract revenue",
    "traction": {"mrr_usd": 41000, "users": 6, "pilot_partners": ["Odisha SDMA", "World Bank South Asia DRR", "ISRO-IN-SPACe MOU"]},
    "funding_ask_usd": 3500000,
    "equity_offered_percent": 14,
    "use_of_funds": "Nanosatellite constellation (3 units via ISRO PSLV), 12 state SDMA contracts, Bangladesh and Vietnam expansion",
    "potential_rating": "High",
    "submitted_at": "2024-07-30T09:00:00Z"
  }
]

def main():
    with open(DATA_PATH, 'r', encoding='utf-8') as f:
        existing = json.load(f)

    existing_ids = {s.get('id','') for s in existing}
    added = 0

    for startup in STARTUPS:
        if startup['id'] not in existing_ids:
            existing.append(startup)
            added += 1
            print(f"  Added: {startup['name']} | {startup['industry']} | {startup['stage']}")
        else:
            print(f"  Updating: {startup['name']}")
            for i, s in enumerate(existing):
                if s.get('id') == startup['id']:
                    existing[i] = startup
                    break

    with open(DATA_PATH, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)

    print(f"\nDone. Added {added} new startups. Total: {len(existing)}")

if __name__ == '__main__':
    main()
